print("23mca022")
print("Aslam Ismail")
print("25-07-24")
import numpy as np
uninitialized_array = np.empty(shape=(2, 3))
print("Uninitialized Array: ")
print(uninitialized_array)
ones_array = np.ones(shape=(2, 3))
print("Array with all elements as 1: ")
print(ones_array)
zeros_array = np.zeros(shape=(2, 3))
print("Array with all elements as 0: ")
print(zeros_array)